### ISSUE TITLE
ValueError when calling compute_transformation_cost function in cost computation step

### ISSUE THREAD

**Issue by khnshn** [gtolomei/ml-feature-tweaking#1]
It should be noted that each row of x_primes, starts with id, three_id, path_id, and path_lenght, so the feature values would start at index 4. currently, the code captures features from index 3 which will cause "ValueError: operands could not be broadcast together with shapes (n, ) (m, )".
so the following code:
```
tree_id = int(row[1][0])
path_id = int(row[1][1])
path_length = int(row[1][2])
x_prime = row[1][3:]
```
should be changed to:
```
tree_id = int(row[1][1])
path_id = int(row[1][2])
path_length = int(row[1][3])
x_prime = row[1][4:]
```

**Comment by gtolomei** [comment]
That's actually true, and this is due to the fact that for confidentiality reasons we have removed any reference to the `id` column, which used to be the very first one.
Thanks for pointing this out! I'm gonna fix this 👍
